#!/usr/bin/env bash


__final__ ()
{
        __inner__ $my_err
}

__inner__ ()
{
        __teardown__
        unset -f __teardown__
        unset -f __inner__
        unset -f __final__
        return $1 
}

__teardown__ ()
{
    rm -rf $my_callback_dir
    for name in $(set | grep ^my_ | cut -d'=' -f1 | grep ^my); do
        [ ! "${name:0:2}" == "my" ] && continue
        unset $name
    done
    unset __handle__
    unset -f my_main
    unset -f my_final
    unset -f my_export
}

__final__
