#!/usr/bin/env bash
this=${BASH_SOURCE[0]}
while [ -L $this ]; do this=$(readlink $this); done
cd $(dirname $this)
src=$PWD/lbin
dst=${BCH0_BIN:-$HOME/.local/bin}
mkdir -p $dst
for name in $(ls $src); do
    real=$src/$name
    link=$dst/$name
    echo creating symlink:
    echo "    real: $real"
    echo "    link: $link"
    [ -L $link ] && rm $link
    ln -s $real $link
done

