[pytest]

addopts = 
    --import-mode=importlib
    -s

#env =
#    THIS=THIS_35047
#    THIS_35047_CALLBACK=/Users/bch/.tmp/callback.THIS_35047.d/callback.sh
#    THIS_35047_NAME=bch.bar
 
pythonpath =
    bch.foo/app
    bch.bar/app

python_files =
    *.py
