#!/usr/bin/env bash

[   "$0" == ${BASH_SOURCE[1]} ] && export this_dot=
[   "$0" == ${BASH_SOURCE[1]} ] && export this_fin=exit
[ ! "$0" == ${BASH_SOURCE[1]} ] && export this_dot=.
[ ! "$0" == ${BASH_SOURCE[1]} ] && export this_fin=return

export this_link=${BASH_SOURCE[1]}
export this=$(readlink ${BASH_SOURCE[1]})

export THIS=THIS_$$

export this_name=$(basename $this_link)
export this_here=$(dirname $this)
export this_usr=$this_here/usr
export this_sys=$this_here/.sys
export this_prj=$(dirname $this_here)
export this_app=$this_here/app/main.py
export this_root=$(dirname $this_prj)
export this_cbdir=$HOME/.tmp/callback.$THIS.d
export this_cb=$this_cbdir/callback.sh

mkdir -p $this_cbdir
touch $this_cb

my_export () { export ${THIS}_$1=$2; }
my_export NAME     $this_name
my_export CALLBACK $this_cb

export __init__="source ${this_sys}/_handle"
source ${this_sys}/_init
source $this_usr/__env__





